CREATE TABLE PROFESOR(
    DNI_PROFESOR VARCHAR (9) NOT NULL,
    NOMBRE VARCHAR (4) NOT NULL,
    AP1 VARCHAR (35) NOT NULL,
    AP2 VARCHAR (35) NULL,
    DIRECCION VARCHAR (30) NOT NULL,
    CUENTA NUMBER (16) NOT NULL,
    CONSTRAINT PK_PROFESOR PRIMARY KEY(DNI_PROFESOR)
);
CREATE TABLE CICLOFORM(
    COD_CICLO NUMBER (9) NOT NULL,
    NOMBRE VARCHAR (4) NOT NULL,
    TIPO VARCHAR (30) NOT NULL,
    CONSTRAINT PK_CICLOFORM PRIMARY KEY(COD_CICLO)
);
CREATE TABLE ASIGNATURA(
    COD_ASIG NUMBER (9) NOT NULL,
    NOMBRE VARCHAR (4) NOT NULL,
    NUMHORAS NUMBER (4) NOT NULL,
    COD_CICLO NUMBER (9) NOT NULL,
    DNI_PROFESOR VARCHAR (9) NOT NULL,
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY(COD_ASIG),
    CONSTRAINT FK_PROFESOR FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESOR(DNI_PROFESOR),
    CONSTRAINT FK_CICLOFORM FOREIGN KEY(COD_CICLO) REFERENCES CICLOFORM(COD_CICLO)
);
CREATE TABLE IDIOMA(
    COD_IDIOMA NUMBER (9) NOT NULL,
    DESCRIPCION VARCHAR (20) NOT NULL,
    CONSTRAINT PK_IDIOMA PRIMARY KEY(COD_IDIOMA)
);
CREATE TABLE ALUMNO(
    DNI_ALUMNO VARCHAR (9) NOT NULL,
    NOMBRE VARCHAR (4) NOT NULL,
    AP1 VARCHAR (35) NOT NULL,
    AP2 VARCHAR (35) NULL,
    DIRECCION VARCHAR (30) NOT NULL,
    EMAIL VARCHAR (30) NOT NULL,
    TELEFONO NUMBER (9) NOT NULL,
    COD_IDIOMA NUMBER (9) NOT NULL,
    CONSTRAINT PK_ALUMNO PRIMARY KEY(DNI_ALUMNO),
    CONSTRAINT FK_IDIOMA FOREIGN KEY(COD_IDIOMA) REFERENCES IDIOMA(COD_IDIOMA)
);
CREATE TABLE MATRICULA(
    DNI_ALUMNO VARCHAR (9) NOT NULL,
    COD_ASIG NUMBER (9) NOT NULL,
    CONSTRAINT PK_MATRICULA PRIMARY KEY(DNI_ALUMNO, COD_ASIG),
    CONSTRAINT FK_ALUMNO FOREIGN KEY(DNI_ALUMNO) REFERENCES ALUMNO(DNI_ALUMNO),
    CONSTRAINT FK_ASIGNATURA FOREIGN KEY(COD_ASIG) REFERENCES ASIGNATURA(COD_ASIG)
);
CREATE TABLE IDIOMAPROF(
    DNI_PROFESOR VARCHAR (9) NOT NULL,
    COD_IDIOMA NUMBER (9) NOT NULL,
    CONSTRAINT PK_IDIOMAPROF PRIMARY KEY(DNI_PROFESOR, COD_IDIOMA),
    CONSTRAINT FK_IDIOMA2 FOREIGN KEY(COD_IDIOMA) REFERENCES IDIOMA(COD_IDIOMA),
    CONSTRAINT FK_PROFESOR2 FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESOR(DNI_PROFESOR)
);