ALTER TABLE DIRECTOR ADD CONSTRAINT UK_DIRECTOR UNIQUE (TELEFONO);
ALTER TABLE VENDEDOR ADD CONSTRAINT UK_VENDEDOR UNIQUE (TELEFONO);
ALTER TABLE CLIENTE ADD CONSTRAINT UK_CLIENTE UNIQUE (TELEFONO);
ALTER TABLE DIRECTOR ADD CONSTRAINT UK_DIRECTOR UNIQUE (EMAIL);
ALTER TABLE VENDEDOR ADD CONSTRAINT UK_VENDEDOR UNIQUE (EMAIL);
ALTER TABLE CLIENTE ADD CONSTRAINT UK_CLIENTE UNIQUE (EMAIL);

ALTER TABLE DIRECTOR MODIFY TELEFONO NUMBER (9);
ALTER TABLE VENDEDOR MODIFY TELEFONO NUMBER (9);
ALTER TABLE CLIENTE MODIFY TELEFONO NUMBER (9);

ALTER TABLE VENTA ADD CONSTRAINT CK_VENTA CHECK (DNI_VENDEDOR!=DNI_CLIENTE);

ALTER TABLE PRODUCTO ADD CONSTRAINT UK_PRODUCTO UNIQUE (DESCRIPCION);
ALTER TABLE PRODUCTO MODIFY CONSTRAINT FK_FAMILIA ON DELETE SET NULL;

ALTER TABLE LINEAVENTA ADD CONSTRAINT CK_LINEAVENTA CHECK (NUMLINEA BETWEEN 1 AND 99);
