--1
CONSTRAINT CK_DATOS_PERSONALES CHECK (VALORES IN ('N', 'D'));
--2
CONSTRAINT CK_DEPARTAMENTO CHECK (NUMPROF BETWEEN 1 AND 30, DESCRIPCION NOCYCLE);
--3
CONSTRAINT CK_DOCTORADO CHECK (FECHA <='1/1/2000' AND FECHA>=NOW);
--4
CONSTRAINT CK_DOCTOR CHECK (TITULO,CALIFICACION BETWEEN 0 AND 10);
--5
CONSTRAINT CK_CURSO CHECK (CURSO BETWEEN 10 AND 500);
