CREATE TABLE TipoDP{
    CODTIPO NUMBER (9) NOT NULL,
    DESCRIPCION VARCHAR (59) NOT NULL,
    CONSTRAINT PK_TipoDP PRIMARY KEY (CODTIPO)
};
ALTER TABLE DatosPersonales MODIFY Telefono NOT NULL;
ALTER TABLE DatosPersonales MODIFY Correo NOT NULL;

ALTER TABLE DatosPersonales ADD CONSTRAINT FK_TipoDP FOREIGN KEY (Tipo) REFERENCES TipoDP(CODTIPO);
ALTER TABLE Director ADD anios NUMBER (2) NOT NULL;
ALTER TABLE COMECIAL DROP COLUMN comision;
ALTER TABLE OFICINA ADD comision NUMBER (3) NOT NULL;

CREATE TABLE TURNO{
    CODTURNO NUMBER (9),
    DESCRIPCION VARCHAR (50),
    CONSTRAINT PK_TURNO PRIMARY KEY (CODTURNO)
};
ALTER TABLE VENDEDOR ADD CONSTRAINT FK_TURNO FOREIGN KEY (TURNO) REFERENCES TURNO(CODTURNO);
CREATE TABLE TEMNATICALIBRO{
    CODTEM NUMBER (9);
    DESCRIPCION VARCHAR (45);
    CONSTRAINT PK_TAMTICALIBRO PRIMARY KEY (CODTEM)
};
ALTER TABLE Libro RENAME PRECIO TO PRECIOACTUAL;
ALTER TABLE Libro RENAME TEMATICA TO TEMNATICALIBRO;
ALTER TABLE LIBRO ADD CONSTRAINT FK_TEMATICALIRBO FOREIGN KEY (CODTEM) REFERENCES TEMATICALIRBO(CODTEM);
