--1
ALTER TABLE CURSO ADD CONSTRAINT FK_CURSO FOREIGN KEY(COD_AULA) REFERENCES AULA(COD_AULA);
--2
--3
ALTER TABLE AULA ADD CONSTRAINT CK_TIPO CHECK (TIPO IN ('Practicas','Audiovisual', 'Grupos pequeños', 'Normal', 'Magna'));
--Se requeriria crear una nueva tabla con una pk y una fk donde se le de sentido a la codificacion.
CREATE TABLE TIPO_AULA(
    COD_TIPO_AULA NUMBER(9),
    NOMBRE VARCHAR (30)
);
INSERT INTO TIPO_AULAM(COD_TIPO_AULA, NOMBRE) VALUES (1,'Practicas');
INSERT INTO TIPO_AULAM(COD_TIPO_AULA, NOMBRE) VALUES (2,'Audiovisual');
INSERT INTO TIPO_AULAM(COD_TIPO_AULA, NOMBRE) VALUES (3,'Grupos pequeños');
INSERT INTO TIPO_AULAM(COD_TIPO_AULA, NOMBRE) VALUES (4,'Normal');
INSERT INTO TIPO_AULAM(COD_TIPO_AULA, NOMBRE) VALUES (5,'Magna');