CREATE TABLE SEDE(
    COD_SEDE NUMBER (9) NOT NULL,
    NOMBRE VARCHAR (6) NOT NULL,
    DIRECCION VARCHAR (30) NOT NULL,
    CONSTRAINT PK_SEDE PRIMARY KEY(COD_SEDE)
);
CREATE TABLE DEPARTAMENTO(
    COD_SEDE NUMBER (9) NOT NULL,
    COD_DEP NUMBER (9) NOT NULL,
    NOMBRE VARCHAR (6) NOT NULL,
    DIRECCION VARCHAR (30) NOT NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY(COD_SEDE, COD_DEP),
    CONSTRAINT FK_SEDE FOREIGN KEY(COD_SEDE) REFERENCES SEDE(COD_SEDE)
);
CREATE TABLE PROGRAMADOR(
    COD_DEP NUMBER (9) NOT NULL,
    DNI_PROGRAMADOR VARCHAR (9) NOT NULL,
    COD_SEDE NUMBER (9) NOT NULL,
    NOMBRE VARCHAR (6) NOT NULL,
    AP1 VARCHAR (35) NOT NULL,
    AP2 VARCHAR (35) NULL,
    DIRECCION VARCHAR (30) NOT NULL,
    CUENTA NUMBER (12) NOT NULL,
    TELEFONO NUMBER (9) NOT NULL,
    DNI_MENTOR  VARCHAR (9) NOT NULL,
    TIPO NUMBER (9) NOT NULL,
    CONSTRAINT PK_PROGRAMADOR PRIMARY KEY(DNI_PROGRAMADOR, COD_DEP, COD_SEDE),
    CONSTRAINT FK_DEPARTAMENTO FOREIGN KEY(COD_DEP, COD_SEDE) REFERENCES DEPARTAMENTO(COD_DEP, COD_SEDE)
);
ALTER TABLE PROGRAMADOR ADD CONSTRAINT FK_MENTOR FOREIGN KEY(DNI_MENTOR, COD_DEP, COD_SEDE) REFERENCES PROGRAMADOR(DNI_PROGRAMADOR, COD_DEP, COD_SEDE);

CREATE TABLE EQUIPO(
    COD_EQUIPO NUMBER (9) NOT NULL,
    DESCRIPCION VARCHAR (40) NOT NULL,
    COD_DEP NUMBER (9) NOT NULL,
    DNI_PROGRAMADOR VARCHAR (9) NOT NULL,
    COD_SEDE NUMBER (9) NOT NULL,
    CONSTRAINT PK_EQUIPO PRIMARY KEY(COD_EQUIPO),
    CONSTRAINT FK_PROGRAMADOR2 FOREIGN KEY(DNI_PROGRAMADOR, COD_DEP, COD_SEDE) REFERENCES PROGRAMADOR(DNI_PROGRAMADOR, COD_DEP, COD_SEDE)
);
CREATE TABLE EQUIPO_PROG(
    DNI_PROGRAMADOR VARCHAR (9) NOT NULL,
    COD_EQUIPO NUMBER (9) NOT NULL,
    CONSTRAINT PK_PROGRAMADOR2 PRIMARY KEY(DNI_PROGRAMADOR),
    CONSTRAINT PK_EQUIPO2 PRIMARY KEY(COD_EQUIPO),
    CONSTRAINT FK_PROGRAMADOR3 FOREIGN KEY(DNI_PROGRAMADOR) REFERENCES PROGRAMADOR(DNI_PROGRAMADOR),
    CONSTRAINT FK_EQUIPO FOREIGN KEY(COD_EQUIPO) REFERENCES EQUIPO(COD_EQUIPO)
);
CREATE TABLE PROYECTO(
    COD_EQUIPO NUMBER (9) NOT NULL,
    COD_PROYECTO NUMBER (9) NOT NULL,
    DESCRIPCION VARCHAR (40) NOT NULL,
    FECHA_INI DATE NOT NULL,
    FECHA_FIN DATE NULL,
    CONSTRAINT PK_EQUIPO3 PRIMARY KEY(COD_EQUIPO),
    CONSTRAINT PK_PROYECTO PRIMARY KEY(COD_PROYECTO),
    CONSTRAINT FK_EQUIPO2 FOREIGN KEY(COD_EQUIPO) REFERENCES EQUIPO(COD_EQUIPO)
);
ALTER TABLE PROGRAMADOR ADD CONSTRAINT FK_PROYECTO FOREIGN KEY(COD_PROYECTO) REFERENCES PROYECTO(COD_PROYECTO)