CREATE TABLE FABRICANTES(
    COD_FAB VARCHAR(9),
    FABRICANTE VARCHAR(30),
    CONSTRAINT PK_FABRICANTE PRIMARY KEY (COD_FAB)
);
CREATE TABLE MARCA(
    COD_MARC VARCHAR (9),
    MARCA VARCHAR (30),
    CONSTRAINT PK_MARCA PRIMARY KEY (COD_MARC)
);
CREATE TABLE VEHICULO(
    COD_VEH VARCHAR (9),
    MODELO VARCHAR (30),
    TIPO VARCHAR (30),
    COLOR VARCHAR (30),
    COD_MARC VARCHAR (9),
    COD_FAB VARCHAR (9),
    CONSTRAINT PK_VEHICULO PRIMARY KEY (COD_VEH),
    CONSTRAINT FK_MARCA FOREIGN KEY (COD_MARC) REFERENCES MARCA (COD_MARC),
    CONSTRAINT FK_FABRICANTE FOREIGN KEY (COD_FAV) REFERENCES FABRICANTE (COD_FAV),
);
CREATE TABLE CLIENTE(
    DNI VARCHAR (9);
    NOMBRE VARCHAR (30),
    PR_APELLIDO VARCHAR (30),
    SG_APELLIDO VARCHAR (30) NULL,
    DOMICILIO VARCHAR (30),
    NUM_TARJETA NUMBER (9),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);
CREATE TABLE CURSO(
    COD_CURSO VARCHAR (9),
    DESCRIPCION VARCHAR (30),
    NUM_HORAS NUMBER (3),
    FECHA DATE,
    CONSTRAINT PK_CURSO PRIMARY KEY (COD_CURSO)
);
CREATE TABLE EMPLEADO(
    DNI VARCHAR (9);
    NOMBRE VARCHAR (30),
    PR_APELLIDO VARCHAR (30),
    SG_APELLIDO VARCHAR (30) NULL,
    DOMICILIO VARCHAR (30),
    NUM_CUENTA NUMBER (9),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI)
);
CREATE TABLE CURSOEMPL(
    DNI VARCHAR (9),
    COD_CURSO VARCHAR (9),
    CONSTRAINT PK_CURSOEMPL PRIMARY KEY (DNI, COD_CURSO),
    CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (DNI) REFERENCES EMPLEADO (DNI)
);
CREATE TABLE OFICINA(
    COD_OFICINA VARCHAR (9),
    DOMICILIO VARCHAR (30),
    TELEFONO NUMBER (9),
    CONSTRAINT PK_OFICINA PRIMARY KEY (COD_OFICINA)
);
CREATE TABLE ALQUILER(
    COD_ALQUILER VARCHAR (39),
    FECHA DATE,
    NUM_DIAS NUMBER (3),
    KM_ACTUAL NUMBER (6),
    KM_ENTREGA NUMBER (6),
    COD_VEH VARCHAR (9),
    DNI_CLIENTE VARCHAR (9),
    COD_OFICINA VARCHAR (9),
    DNI_EMPLEADO VARCHAR (9),
    CONSTRAINT PK_ALQUILER PRIMARY KEY (COD_ALQUILER),
    CONSTRAINT FK_VEHICULO FOREIGN KEY (COD_VEH) REFERENCES VEHICULO (COD_VEH),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (DNI) REFERENCES CLIENTE (DNI_CLIENTE),
    CONSTRAINT FK_OFICINA FOREIGN KEY (COD_OFICINA) REFERENCES OFICINA (COD_OFICINA),
    CONSTRAINT FK_EPLEADO_2 FOREIGN KEY (DNI) REFERENCES  EMPLEADO (DNI_EMPLEADO)
);
CREATE TABLE OFICINASALQ(
    COD_ALQUILER VARCHAR (9),
    COD_OFICINA VARCHAR (9),
    CONSTRAINT PK_OFICINASALQ PRIMARY KEY (COD_OFICINA, COD_ALQUILER),
    CONSTRAINT FK_ALQUILER FOREIGN KEY (COD_ALQUILER) REFERENCES ALQUILER (COD_ALQUILER),
    CONSTRAINT FK_OFICINA_2 FOREIGN KEY (COD_OFICINA) REFERENCES OFICINA (COD_OFICINA)
);